import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";

export default defineConfig({
    server: {
        host: true,
        port: 5173,
        strictPort: true,
        hmr: {
            host: 'localhost',
            port: 5173,
        },
    },    plugins: [
        laravel({
            input: [
                "resources/css/custom-style.css",
                "resources/js/rolesPermissions/createAssignRole.js",
                "resources/css/app.css",
                "resources/scss/style.scss",
                "resources/js/profile/dateFillter.js",
                "resources/js/profile/listing-vivier-talents.js",
                "resources/js/dashboard/dateFilter.js",
                "resources/js/app.js",
                "resources/js/client/create-edit-client.js",
                "resources/js/client/create-edit-client-finance.js",
                "resources/js/client/create-edit-client-filiale.js",
                "resources/js/client/create-edit-client-evaluator.js",
                "resources/js/event/listing.js",
                "resources/js/profile/listing.js",
                "resources/js/profile/create-edit.js",
                "resources/js/candidatePortal/profile/create-edit.js",
                "resources/js/client/listing.js",
                "resources/js/jobOffer/listing.js",
                "resources/js/jobOffer/create.js",
                "resources/js/jobOffer/confirmeStatusAnnuler.js",
                "resources/js/jobOffer/history.js",
                // 'resources/js/jobOffre/create.js',
                "resources/js/activityArea/listing.js",
                "resources/js/activityArea/view.js",
                "resources/js/activityArea/create.js",
                // 'resources/js/activityArea/delete.js',
                "resources/js/activityArea/edit.js",
                "resources/js/evaluator/create-edit-evaluator.js",
                "resources/js/profession/listing.js",
                "resources/js/diplomaoption/create-edit.js",
                "resources/js/diplomaoption/listing.js",
                "resources/js/matching/listing.js",
                "resources/js/trackingApplication/listing.js",
                "resources/js/trackingApplication/kanbanByStatus.js",
                "resources/js/candidate/create-edit.js",
                "resources/js/candidate/listing.js",
                "resources/js/evaluation/create-edit.js",
                "resources/js/technicalTest/listing.js",
                "resources/js/technicalTest/create-edit.js",
                "resources/js/technicalTest/fiche-candidate-test.js",
                "resources/js/evaluation/create-edit.js",
                "resources/js/technicalTest/listing.js",
                "resources/js/technicalTest/result-tests.js",
                "resources/js/filiale/create.js",
                "resources/js/agence/listing.js",
                "resources/js/agence/create.js",
                "resources/js/companie/listing.js",
                "resources/js/companie/edit.js",
                "resources/js/profileFolders/listing.js",
                "resources/js/profileFolders/create.js",
                "resources/js/competenceTechnique/listing.js",
                "resources/js/competenceLinguistique/listing.js",
                "resources/js/competencePersonnelle/listing.js",
                "resources/js/competenceTechnique/create.js",
                "resources/js/competenceLinguistique/create.js",
                "resources/js/competencePersonnelle/create.js",
                "resources/js/candidatePortal/fiche-candidate.js",
                "resources/js/candidatePortal/listing.js",
                "resources/js/candidatePortal/listingMatching.js",
                "resources/js/user/listing.js",
                "resources/js/rolesPermissions/modulePermissions",
                "resources/js/recruitmentCost/listing.js",
                "resources/js/recruitmentCost/create-edit.js",
                // Portal Client
                "resources/js/clientPortal/trackingApplication/listing.js",
                "resources/js/clientPortal/trackingApplication/kanbanByStatus.js",
                "resources/js/matching/print.js",
                "resources/js/matching/previewDetail.js",
                "resources/js/profile/preview-vivier.js",
                "resources/js/technicalTest/start-test.js",
                "resources/js/evaluator/listing-evaluator.js",

                "resources/js/matching/preview.js",
                "resources/js/client/create-edit-client-site.js",
                "resources/js/client/create-edit-admin-user.js"
            ],
            refresh: true,
        }),
    ],
});
