<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    public function run()
    {
        $countries = [
            ['name' => 'Afghanistan', 'code_iso3' => 'AFG', 'code' => 'AF'],
            ['name' => 'Albanie', 'code_iso3' => 'ALB', 'code' => 'AL'],
            ['name' => 'Algerie', 'code_iso3' => 'DZA', 'code' => 'DZ'],
            ['name' => 'Samoa americaines', 'code_iso3' => 'ASM', 'code' => 'AS'],
            ['name' => 'Andorre', 'code_iso3' => 'AND', 'code' => 'AD'],
            ['name' => 'Angola', 'code_iso3' => 'AGO', 'code' => 'AO'],
            ['name' => 'Anguilla', 'code_iso3' => 'AIA', 'code' => 'AI'],
            ['name' => 'Antigua et Barbuda', 'code_iso3' => 'ATG', 'code' => 'AG'],
            ['name' => 'Argentine', 'code_iso3' => 'ARG', 'code' => 'AR'],
            ['name' => 'Armenie', 'code_iso3' => 'ARM', 'code' => 'AM'],
            ['name' => 'Aruba', 'code_iso3' => 'ABW', 'code' => 'AW'],
            ['name' => 'Australie', 'code_iso3' => 'AUS', 'code' => 'AU'],
            ['name' => 'Autriche', 'code_iso3' => 'AUT', 'code' => 'AT'],
            ['name' => 'Azerbaidjan', 'code_iso3' => 'AZE', 'code' => 'AZ'],
            ['name' => 'Bahamas ', 'code_iso3' => 'BHS', 'code' => 'BS'],
            ['name' => 'Bahrein', 'code_iso3' => 'BHR', 'code' => 'BH'],
            ['name' => 'Bangladesh', 'code_iso3' => 'BGD', 'code' => 'BD'],
            ['name' => 'Barbade', 'code_iso3' => 'BRB', 'code' => 'BB'],
            ['name' => 'Bielorussie', 'code_iso3' => 'BLR', 'code' => 'BY'],
            ['name' => 'Belgique', 'code_iso3' => 'BEL', 'code' => 'BE'],
            ['name' => 'Belize', 'code_iso3' => 'BLZ', 'code' => 'BZ'],
            ['name' => 'Benin', 'code_iso3' => 'BEN', 'code' => 'BJ'],
            ['name' => 'Bermudes', 'code_iso3' => 'BMU', 'code' => 'BM'],
            ['name' => 'Bhoutan', 'code_iso3' => 'BTN', 'code' => 'BT'],
            ['name' => 'Bolivie', 'code_iso3' => 'BOL', 'code' => 'BO'],
            ['name' => 'Bonaire Saba et Saint Eustache', 'code_iso3' => 'BES', 'code' => 'BQ'],
            ['name' => 'Bosnie Herzegovine', 'code_iso3' => 'BIH', 'code' => 'BA'],
            ['name' => 'Botswana', 'code_iso3' => 'BWA', 'code' => 'BW'],
            ['name' => 'Bresil', 'code_iso3' => 'BRA', 'code' => 'BR'],
            ['name' => 'Brunei', 'code_iso3' => 'BRN', 'code' => 'BN'],
            ['name' => 'Bulgarie', 'code_iso3' => 'BGR', 'code' => 'BG'],
            ['name' => 'Burkina Faso', 'code_iso3' => 'BFA', 'code' => 'BF'],
            ['name' => 'Myanmar(Birmanie)', 'code_iso3' => 'MMR', 'code' => 'MM'],
            ['name' => 'Burundi', 'code_iso3' => 'BDI', 'code' => 'BI'],
            ['name' => 'Cap Vert', 'code_iso3' => 'CPV', 'code' => 'CV'],
            ['name' => 'Cambodge', 'code_iso3' => 'KHM', 'code' => 'KH'],
            ['name' => 'Cameroun', 'code_iso3' => 'CMR', 'code' => 'CM'],
            ['name' => 'Canada', 'code_iso3' => 'CAN', 'code' => 'CA'],
            ['name' => 'Iles Caimans', 'code_iso3' => 'CYM', 'code' => 'KY'],
            ['name' => 'Republique centrafricaine', 'code_iso3' => 'CAF', 'code' => 'CF'],
            ['name' => 'Tchad', 'code_iso3' => 'TCD', 'code' => 'TD'],
            ['name' => 'Chili', 'code_iso3' => 'CHL', 'code' => 'CL'],
            ['name' => 'Chine', 'code_iso3' => 'CHN', 'code' => 'CN'],
            ['name' => 'Ile Christmas', 'code_iso3' => 'CXR', 'code' => 'CX'],
            ['name' => 'Colombie', 'code_iso3' => 'COL', 'code' => 'CO'],
            ['name' => 'Comores', 'code_iso3' => 'COM', 'code' => 'KM'],
            ['name' => 'Republique du congo', 'code_iso3' => 'COG', 'code' => 'CG'],
            ['name' => 'Republique democratique du congo', 'code_iso3' => 'COD', 'code' => 'CD'],
            ['name' => 'Iles Cook', 'code_iso3' => 'COK', 'code' => 'CK'],
            ['name' => 'Costa Rica', 'code_iso3' => 'CRI', 'code' => 'CR'],
            ['name' => 'Cote dIvoire', 'code_iso3' => 'CIV', 'code' => 'CI'],
            ['name' => 'Croatie', 'code_iso3' => 'HRV', 'code' => 'HR'],
            ['name' => 'Cuba', 'code_iso3' => 'CUB', 'code' => 'CU'],
            ['name' => 'Curacao', 'code_iso3' => 'CUW', 'code' => 'CW'],
            ['name' => 'Chypre', 'code_iso3' => 'CYP', 'code' => 'CY'],
            ['name' => 'Tchequie', 'code_iso3' => 'CZE', 'code' => 'CZ'],
            ['name' => 'Danemark', 'code_iso3' => 'DNK', 'code' => 'DK'],
            ['name' => 'Djibouti', 'code_iso3' => 'DJI', 'code' => 'DJ'],
            ['name' => 'Dominique', 'code_iso3' => 'DMA', 'code' => 'DM'],
            ['name' => 'Republique dominicaine', 'code_iso3' => 'DOM', 'code' => 'DO'],
            ['name' => 'Equateur', 'code_iso3' => 'ECU', 'code' => 'EC'],
            ['name' => 'Egypte', 'code_iso3' => 'EGY', 'code' => 'EG'],
            ['name' => 'Salvador', 'code_iso3' => 'SLV', 'code' => 'SV'],
            ['name' => 'Guinee equatoriale', 'code_iso3' => 'GNQ', 'code' => 'GQ'],
            ['name' => 'Erythree', 'code_iso3' => 'ERI', 'code' => 'ER'],
            ['name' => 'Estonie', 'code_iso3' => 'EST', 'code' => 'EE'],
            ['name' => 'Eswatini', 'code_iso3' => 'SWZ', 'code' => 'SZ'],
            ['name' => 'Ethiopie', 'code_iso3' => 'ETH', 'code' => 'ET'],
            ['name' => 'Iles Falkland (malvinas)', 'code_iso3' => 'FLK', 'code' => 'FK'],
            ['name' => 'Iles Feroe', 'code_iso3' => 'FRO', 'code' => 'FO'],
            ['name' => 'Fidji', 'code_iso3' => 'FJI', 'code' => 'FJ'],
            ['name' => 'Finlande', 'code_iso3' => 'FIN', 'code' => 'FI'],
            ['name' => 'France', 'code_iso3' => 'FRA', 'code' => 'FR'],
            ['name' => 'Guyane francaise', 'code_iso3' => 'GUF', 'code' => 'GF'],
            ['name' => 'Polynesie francaise', 'code_iso3' => 'PYF', 'code' => 'PF'],
            ['name' => 'Gabon', 'code_iso3' => 'GAB', 'code' => 'GA'],
            ['name' => 'Gambie ', 'code_iso3' => 'GMB', 'code' => 'GM'],
            ['name' => 'Georgie', 'code_iso3' => 'GEO', 'code' => 'GE'],
            ['name' => 'Allemagne', 'code_iso3' => 'DEU', 'code' => 'DE'],
            ['name' => 'Ghana', 'code_iso3' => 'GHA', 'code' => 'GH'],
            ['name' => 'Gibraltar', 'code_iso3' => 'GIB', 'code' => 'GI'],
            ['name' => 'Grece', 'code_iso3' => 'GRC', 'code' => 'GR'],
            ['name' => 'Groenland', 'code_iso3' => 'GRL', 'code' => 'GL'],
            ['name' => 'Grenade', 'code_iso3' => 'GRD', 'code' => 'GD'],
            ['name' => 'Guadeloupe', 'code_iso3' => 'GLP', 'code' => 'GP'],
            ['name' => 'Guam', 'code_iso3' => 'GUM', 'code' => 'GU'],
            ['name' => 'Guatemala', 'code_iso3' => 'GTM', 'code' => 'GT'],
            ['name' => 'Guernesey', 'code_iso3' => 'GGY', 'code' => 'GG'],
            ['name' => 'Guinee', 'code_iso3' => 'GIN', 'code' => 'GN'],
            ['name' => 'Guinee bissau', 'code_iso3' => 'GNB', 'code' => 'GW'],
            ['name' => 'Guyane britannique', 'code_iso3' => 'GUY', 'code' => 'GY'],
            ['name' => 'Haiti', 'code_iso3' => 'HTI', 'code' => 'HT'],
            ['name' => 'Honduras', 'code_iso3' => 'HND', 'code' => 'HN'],
            ['name' => 'Hong Kong', 'code_iso3' => 'HKG', 'code' => 'HK'],
            ['name' => 'Hongrie', 'code_iso3' => 'HUN', 'code' => 'HU'],
            ['name' => 'Islande', 'code_iso3' => 'ISL', 'code' => 'IS'],
            ['name' => 'Inde', 'code_iso3' => 'IND', 'code' => 'IN'],
            ['name' => 'Indonesie', 'code_iso3' => 'IDN', 'code' => 'ID'],
            ['name' => 'Iran', 'code_iso3' => 'IRN', 'code' => 'IR'],
            ['name' => 'Irak', 'code_iso3' => 'IRQ', 'code' => 'IQ'],
            ['name' => 'Irlande', 'code_iso3' => 'IRL', 'code' => 'IE'],
            ['name' => 'Ile de Man', 'code_iso3' => 'IMN', 'code' => 'IM'],
            ['name' => 'Italie', 'code_iso3' => 'ITA', 'code' => 'IT'],
            ['name' => 'Jamaique', 'code_iso3' => 'JAM', 'code' => 'JM'],
            ['name' => 'Japon', 'code_iso3' => 'JPN', 'code' => 'JP'],
            ['name' => 'Jersey', 'code_iso3' => 'JEY', 'code' => 'JE'],
            ['name' => 'Jordanie', 'code_iso3' => 'JOR', 'code' => 'JO'],
            ['name' => 'Kazakhstan', 'code_iso3' => 'KAZ', 'code' => 'KZ'],
            ['name' => 'Kenya', 'code_iso3' => 'KEN', 'code' => 'KE'],
            ['name' => 'Kiribati', 'code_iso3' => 'KIR', 'code' => 'KI'],
            ['name' => 'Coree du Nord', 'code_iso3' => 'PRK', 'code' => 'KP'],
            ['name' => 'Coree du Sud', 'code_iso3' => 'KOR', 'code' => 'KR'],
            ['name' => 'Kosovo', 'code_iso3' => 'XKS', 'code' => 'XK'],
            ['name' => 'Koweit', 'code_iso3' => 'KWT', 'code' => 'KW'],
            ['name' => 'Kirghizistan', 'code_iso3' => 'KGZ', 'code' => 'KG'],
            ['name' => 'Laos', 'code_iso3' => 'LAO', 'code' => 'LA'],
            ['name' => 'Lettonie', 'code_iso3' => 'LVA', 'code' => 'LV'],
            ['name' => 'Liban', 'code_iso3' => 'LBN', 'code' => 'LB'],
            ['name' => 'Lesotho', 'code_iso3' => 'LSO', 'code' => 'LS'],
            ['name' => 'Liberia', 'code_iso3' => 'LBR', 'code' => 'LR'],
            ['name' => 'Libye', 'code_iso3' => 'LBY', 'code' => 'LY'],
            ['name' => 'Liechtenstein', 'code_iso3' => 'LIE', 'code' => 'LI'],
            ['name' => 'Lituanie', 'code_iso3' => 'LTU', 'code' => 'LT'],
            ['name' => 'Luxembourg', 'code_iso3' => 'LUX', 'code' => 'LU'],
            ['name' => 'Macao', 'code_iso3' => 'MAC', 'code' => 'MO'],
            ['name' => 'Madagascar', 'code_iso3' => 'MDG', 'code' => 'MG'],
            ['name' => 'Malawi', 'code_iso3' => 'MWI', 'code' => 'MW'],
            ['name' => 'Malaisie', 'code_iso3' => 'MYS', 'code' => 'MY'],
            ['name' => 'Maldives', 'code_iso3' => 'MDV', 'code' => 'MV'],
            ['name' => 'Mali', 'code_iso3' => 'MLI', 'code' => 'ML'],
            ['name' => 'Malte', 'code_iso3' => 'MLT', 'code' => 'MT'],
            ['name' => 'Iles Marshall', 'code_iso3' => 'MHL', 'code' => 'MH'],
            ['name' => 'Martinique', 'code_iso3' => 'MTQ', 'code' => 'MQ'],
            ['name' => 'Mauritanie', 'code_iso3' => 'MRT', 'code' => 'MR'],
            ['name' => 'Maurice', 'code_iso3' => 'MUS', 'code' => 'MU'],
            ['name' => 'Mayotte', 'code_iso3' => 'MYT', 'code' => 'YT'],
            ['name' => 'Mexique', 'code_iso3' => 'MEX', 'code' => 'MX'],
            ['name' => 'Etats federes de Micronesie', 'code_iso3' => 'FSM', 'code' => 'FM'],
            ['name' => 'Moldavie', 'code_iso3' => 'MDA', 'code' => 'MD'],
            ['name' => 'Monaco', 'code_iso3' => 'MCO', 'code' => 'MC'],
            ['name' => 'Mongolie', 'code_iso3' => 'MNG', 'code' => 'MN'],
            ['name' => 'Montenegro', 'code_iso3' => 'MNE', 'code' => 'ME'],
            ['name' => 'Montserrat', 'code_iso3' => 'MSR', 'code' => 'MS'],
            ['name' => 'Maroc', 'code_iso3' => 'MAR', 'code' => 'MA'],
            ['name' => 'Mozambique', 'code_iso3' => 'MOZ', 'code' => 'MZ'],
            ['name' => 'Namibie', 'code_iso3' => 'NAM', 'code' => 'NA'],
            ['name' => 'Nauru', 'code_iso3' => 'NRU', 'code' => 'NR'],
            ['name' => 'Nepal', 'code_iso3' => 'NPL', 'code' => 'NP'],
            ['name' => 'Pays Bas', 'code_iso3' => 'NLD', 'code' => 'NL'],
            ['name' => 'Nouvelle Caledonie', 'code_iso3' => 'NCL', 'code' => 'NC'],
            ['name' => 'Nouvelle Zelande', 'code_iso3' => 'NZL', 'code' => 'NZ'],
            ['name' => 'Nicaragua', 'code_iso3' => 'NIC', 'code' => 'NI'],
            ['name' => 'Niger', 'code_iso3' => 'NER', 'code' => 'NE'],
            ['name' => 'Nigeria', 'code_iso3' => 'NGA', 'code' => 'NG'],
            ['name' => 'Niue', 'code_iso3' => 'NIU', 'code' => 'NU'],
            ['name' => 'Ile Norfolk', 'code_iso3' => 'NFK', 'code' => 'NF'],
            ['name' => 'Macedoine du Nord', 'code_iso3' => 'MKD', 'code' => 'MK'],
            ['name' => 'Iles Mariannes du Nord', 'code_iso3' => 'MNP', 'code' => 'MP'],
            ['name' => 'Norvege', 'code_iso3' => 'NOR', 'code' => 'NO'],
            ['name' => 'Oman', 'code_iso3' => 'OMN', 'code' => 'OM'],
            ['name' => 'Palestine', 'code_iso3' => 'PSE', 'code' => 'PS'],
            ['name' => 'Pakistan', 'code_iso3' => 'PAK', 'code' => 'PK'],
            ['name' => 'Palaos', 'code_iso3' => 'PLW', 'code' => 'PW'],
            ['name' => 'Panama', 'code_iso3' => 'PAN', 'code' => 'PA'],
            ['name' => 'Papouasie Nouvelle Guinee', 'code_iso3' => 'PNG', 'code' => 'PG'],
            ['name' => 'Paraguay', 'code_iso3' => 'PRY', 'code' => 'PY'],
            ['name' => 'Perou', 'code_iso3' => 'PER', 'code' => 'PE'],
            ['name' => 'Philippines', 'code_iso3' => 'PHL', 'code' => 'PH'],
            ['name' => 'Iles Pitcairn', 'code_iso3' => 'PCN', 'code' => 'PN'],
            ['name' => 'Pologne', 'code_iso3' => 'POL', 'code' => 'PL'],
            ['name' => 'Portugal', 'code_iso3' => 'PRT', 'code' => 'PT'],
            ['name' => 'Porto Rico', 'code_iso3' => 'PRI', 'code' => 'PR'],
            ['name' => 'Qatar', 'code_iso3' => 'QAT', 'code' => 'QA'],
            ['name' => 'Reunion', 'code_iso3' => 'REU', 'code' => 'RE'],
            ['name' => 'Roumanie', 'code_iso3' => 'ROU', 'code' => 'RO'],
            ['name' => 'Russie', 'code_iso3' => 'RUS', 'code' => 'RU'],
            ['name' => 'Rwanda', 'code_iso3' => 'RWA', 'code' => 'RW'],
            ['name' => 'Saint Barthelemy', 'code_iso3' => 'BLM', 'code' => 'BL'],
            ['name' => 'Sainte Helene Ascension et Tristan da Cunha', 'code_iso3' => 'SHN', 'code' => 'SH'],
            ['name' => 'Saint Christophe et Nieves', 'code_iso3' => 'KNA', 'code' => 'KN'],
            ['name' => 'Sainte Lucie', 'code_iso3' => 'LCA', 'code' => 'LC'],
            ['name' => 'Saint Pierre et Miquelon', 'code_iso3' => 'SPM', 'code' => 'PM'],
            ['name' => 'Saint Vincent et les Grenadines', 'code_iso3' => 'VCT', 'code' => 'VC'],
            ['name' => 'Samoa', 'code_iso3' => 'WSM', 'code' => 'WS'],
            ['name' => 'Saint Marin', 'code_iso3' => 'SMR', 'code' => 'SM'],
            ['name' => 'Sao tome et principe', 'code_iso3' => 'STP', 'code' => 'ST'],
            ['name' => 'Arabie Saoudite', 'code_iso3' => 'SAU', 'code' => 'SA'],
            ['name' => 'Senegal', 'code_iso3' => 'SEN', 'code' => 'SN'],
            ['name' => 'Serbie', 'code_iso3' => 'SRB', 'code' => 'RS'],
            ['name' => 'Seychelles', 'code_iso3' => 'SYC', 'code' => 'SC'],
            ['name' => 'Sierra Leone', 'code_iso3' => 'SLE', 'code' => 'SL'],
            ['name' => 'Singapour', 'code_iso3' => 'SGP', 'code' => 'SG'],
            ['name' => 'Saint Martin', 'code_iso3' => 'SXM', 'code' => 'SX'],
            ['name' => 'Slovaquie', 'code_iso3' => 'SVK', 'code' => 'SK'],
            ['name' => 'Slovenie', 'code_iso3' => 'SVN', 'code' => 'SI'],
            ['name' => 'Iles Salomon', 'code_iso3' => 'SLB', 'code' => 'SB'],
            ['name' => 'Somalie', 'code_iso3' => 'SOM', 'code' => 'SO'],
            ['name' => 'Afrique du Sud', 'code_iso3' => 'ZAF', 'code' => 'ZA'],
            ['name' => 'Georgie du Sud et iles Sandwich du Sud', 'code_iso3' => 'SGS', 'code' => 'GS'],
            ['name' => 'Soudan du Sud', 'code_iso3' => 'SSD', 'code' => 'SS'],
            ['name' => 'Espagne', 'code_iso3' => 'ESP', 'code' => 'ES'],
            ['name' => 'Sri Lanka', 'code_iso3' => 'LKA', 'code' => 'LK'],
            ['name' => 'Soudan', 'code_iso3' => 'SDN', 'code' => 'SD'],
            ['name' => 'Suriname', 'code_iso3' => 'SUR', 'code' => 'SR'],
            ['name' => 'Svalbard', 'code_iso3' => 'XSV', 'code' => 'XR'],
            ['name' => 'Suede', 'code_iso3' => 'SWE', 'code' => 'SE'],
            ['name' => 'Suisse', 'code_iso3' => 'CHE', 'code' => 'CH'],
            ['name' => 'Syrie', 'code_iso3' => 'SYR', 'code' => 'SY'],
            ['name' => 'Taiwan', 'code_iso3' => 'TWN', 'code' => 'TW'],
            ['name' => 'Tadjikistan', 'code_iso3' => 'TJK', 'code' => 'TJ'],
            ['name' => 'Tanzanie', 'code_iso3' => 'TZA', 'code' => 'TZ'],
            ['name' => 'Thailande', 'code_iso3' => 'THA', 'code' => 'TH'],
            ['name' => 'Timor oriental', 'code_iso3' => 'TLS', 'code' => 'TL'],
            ['name' => 'Togo', 'code_iso3' => 'TGO', 'code' => 'TG'],
            ['name' => 'Tonga', 'code_iso3' => 'TON', 'code' => 'TO'],
            ['name' => 'Trinite et Tobago', 'code_iso3' => 'TTO', 'code' => 'TT'],
            ['name' => 'Tunisie', 'code_iso3' => 'TUN', 'code' => 'TN'],
            ['name' => 'Turquie', 'code_iso3' => 'TUR', 'code' => 'TR'],
            ['name' => 'Turkmenistan', 'code_iso3' => 'TKM', 'code' => 'TM'],
            ['name' => 'Iles Turques et Caiques', 'code_iso3' => 'TCA', 'code' => 'TC'],
            ['name' => 'Tuvalu', 'code_iso3' => 'TUV', 'code' => 'TV'],
            ['name' => 'Iles Vierges', 'code_iso3' => 'VIR', 'code' => 'VI'],
            ['name' => 'Ouganda', 'code_iso3' => 'UGA', 'code' => 'UG'],
            ['name' => 'Ukraine', 'code_iso3' => 'UKR', 'code' => 'UA'],
            ['name' => 'Emirats arabes unis', 'code_iso3' => 'ARE', 'code' => 'AE'],
            ['name' => 'Royaume Uni', 'code_iso3' => 'GBR', 'code' => 'GB'],
            ['name' => 'Etats Unis', 'code_iso3' => 'USA', 'code' => 'US'],
            ['name' => 'Uruguay', 'code_iso3' => 'URY', 'code' => 'UY'],
            ['name' => 'Ouzbekistan', 'code_iso3' => 'UZB', 'code' => 'UZ'],
            ['name' => 'Vanuatu', 'code_iso3' => 'VUT', 'code' => 'VU'],
            ['name' => 'Vatican', 'code_iso3' => 'VAT', 'code' => 'VA'],
            ['name' => 'Venezuela', 'code_iso3' => 'VEN', 'code' => 'VE'],
            ['name' => 'Viet Nam', 'code_iso3' => 'VNM', 'code' => 'VN'],
            ['name' => 'Iles Vierges britanniques', 'code_iso3' => 'VGB', 'code' => 'VG'],
            ['name' => 'Wallis et Futuna', 'code_iso3' => 'WLF', 'code' => 'WF'],
            ['name' => 'Yemen', 'code_iso3' => 'YEM', 'code' => 'YE'],
            ['name' => 'Zambie', 'code_iso3' => 'ZMB', 'code' => 'ZM'],
            ['name' => 'Zimbabwe', 'code_iso3' => 'ZWE', 'code' => 'ZW']

        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
