<?php

namespace Database\Seeders;

use App\Models\DiplomaOption;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NewDiplomaOptionsSeeder extends Seeder
{
    public function run()
    {
      $diplomaOptions = [

    // 'Diplôme de Baccalauréat'
        ['label' => 'Sciences Physiques'],
        ['label' => 'Sciences Mathématiques A'],
        ['label' => 'Sciences Mathématiques B'],
        ['label' => 'Sciences de la Vie et de la Terre'],
        ['label' => 'Sciences Économiques'],
        ['label' => 'Sciences de Gestion Comptable'],
        ['label' => 'Lettres Modernes'],
        ['label' => 'Lettres et Sciences Humaines'],
        ['label' => 'Sciences Agronomiques'],
        ['label' => 'Sciences et Technologies Électriques'],
        ['label' => 'Sciences et Technologies Mécaniques'],
        ['label' => 'Sciences et Technologies Sanitaires'],
        ['label' => 'Sciences de l’Ingénieur'],

    // 'Brevet de Technicien Supérieur (BTS)'
        ['label' => 'Génie Électrique'],
        ['label' => 'Génie Mécanique et Productique'],
        ['label' => 'Gestion des Entreprises'],
        ['label' => 'Informatique Développement'],
        ['label' => 'Commerce International'],
        ['label' => 'Techniques de Management'],
        ['label' => 'Comptabilité et Gestion'],
        ['label' => 'Maintenance Industrielle'],
        ['label' => 'Électromécanique des Systèmes Automatisés'],
        ['label' => 'Marketing et Communication'],
        ['label' => 'Gestion des Ressources Humaines'],
        ['label' => 'Assurance et Banque'],
        ['label' => 'Tourisme et Hôtellerie'],

    // 'Diplôme Universitaire de Technologie (DUT)'
        ['label' => 'Génie Informatique'],
        ['label' => 'Génie Électrique'],
        ['label' => 'Techniques de Commercialisation'],
        ['label' => 'Génie Mécanique et Productique'],
        ['label' => 'Statistique et Informatique Décisionnelle'],
        ['label' => 'Gestion des Entreprises et Administrations'],
        ['label' => 'Réseaux et Télécommunications'],
        ['label' => 'Techniques de Gestion de la Production'],
        ['label' => 'Hygiène, Sécurité et Environnement'],

    // 'Diplôme d’Études Universitaires Générales (DEUG)'
        ['label' => 'Mathématiques et Informatique'],
        ['label' => 'Sciences de la Vie'],
        ['label' => 'Chimie-Biologie'],
        ['label' => 'Sciences Économiques et Gestion'],
        ['label' => 'Lettres Françaises'],
        ['label' => 'Études Islamiques'],
        ['label' => 'Droit Public'],
        ['label' => 'Droit Privé'],
        ['label' => 'Histoire et Géographie'],
        ['label' => 'Philosophie'],
        ['label' => 'Chimie'],
        ['label' => 'Physique'],

    // 'Diplôme de Technicien'
        ['label' => 'Secrétariat de Direction'],
        ['label' => 'Comptabilité d’Entreprise'],
        ['label' => 'Bureautique'],
        ['label' => 'Maintenance Informatique'],
        ['label' => 'Électromécanique'],
        ['label' => 'Technicien de Réseaux'],
        ['label' => 'Infographie'],
        ['label' => 'Assistance Administrative'],
        ['label' => 'Technicien Agricole'],
        ['label' => 'Technicien en Marketing'],
        ['label' => 'Technicien en Assurance'],
        ['label' => 'Technicien en Banque'],

    // 'Diplôme de Technicien Spécialisé'
        ['label' => 'Développement Informatique'],
        ['label' => 'Gestion des Entreprises'],
        ['label' => 'Administration Réseaux'],
        ['label' => 'Commerce'],
        ['label' => 'Finance et Comptabilité'],
        ['label' => 'Maintenance Industrielle'],
        ['label' => 'Topographie et Géomatique'],
        ['label' => 'Multimédia et Infographie'],
        ['label' => 'Ressources Humaines'],
        ['label' => 'Management Logistique'],
        ['label' => 'Marketing Digital'],
        ['label' => 'Assurance et Assurance Santé'],
        ['label' => 'Banque et Finance de Marché'],

    // 'Licence'
        ['label' => 'Licence en Informatique'],
        ['label' => 'Licence en Génie Logiciel'],
        ['label' => 'Licence en Sciences Mathématiques'],
        ['label' => 'Licence en Mathématiques Appliquées'],
        ['label' => 'Licence en Physique'],
        ['label' => 'Licence en Physique-Chimie'],
        ['label' => 'Licence en Chimie'],
        ['label' => 'Licence en Biologie'],
        ['label' => 'Licence en Sciences de la Vie'],
        ['label' => 'Licence en Sciences de l’Environnement'],
        ['label' => 'Licence en Sciences de l’Ingénieur'],
        ['label' => 'Licence en Géologie'],
        ['label' => 'Licence en Économie'],
        ['label' => 'Licence en Économie et Gestion'],
        ['label' => 'Licence en Gestion des Entreprises'],
        ['label' => 'Licence en Comptabilité'],
        ['label' => 'Licence en Finance'],
        ['label' => 'Licence en Droit Public'],
        ['label' => 'Licence en Droit Privé'],
        ['label' => 'Licence en Droit des Affaires'],
        ['label' => 'Licence en Droit International'],
        ['label' => 'Licence en Science Politique'],
        ['label' => 'Licence en Administration Publique'],
        ['label' => 'Licence en Relations Internationales'],
        ['label' => 'Licence en Lettres Françaises'],
        ['label' => 'Licence en Lettres Anglaises'],
        ['label' => 'Licence en Langues Étrangères Appliquées'],
        ['label' => 'Licence en Histoire'],
        ['label' => 'Licence en Géographie'],
        ['label' => 'Licence en Philosophie'],
        ['label' => 'Licence en Communication'],
        ['label' => 'Licence en Journalisme'],
        ['label' => 'Licence en Sciences de l’Éducation'],
        ['label' => 'Licence en Pédagogie'],
        ['label' => 'Licence en Psychologie'],
        ['label' => 'Licence en Sociologie'],
        ['label' => 'Licence en Travail Social'],
        ['label' => 'Licence en Théâtre et Arts du Spectacle'],
        ['label' => 'Licence en Musique'],
        ['label' => 'Licence en Design Graphique'],
        ['label' => 'Licence en Architecture'],
        ['label' => 'Licence en Urbanisme'],
        ['label' => 'Licence en Tourisme et Hôtellerie'],
        ['label' => 'Licence en Logistique et Transport'],
        ['label' => 'Licence en Marketing'],
        ['label' => 'Licence en Commerce International'],
        ['label' => 'Licence en Gestion des Ressources Humaines'],
        ['label' => 'Licence en Qualité Sécurité Environnement (QSE)'],



    // 'Licence Professionnelle'
        ['label' => 'LP en Développement Web et Mobile'],
        ['label' => 'LP en Réseaux Informatiques'],
        ['label' => 'LP en Marketing Digital'],
        ['label' => 'LP en Management des RH'],
        ['label' => 'LP en Finance et Comptabilité'],
        ['label' => 'LP en Qualité, Sécurité, Environnement (QSE)'],
        ['label' => 'LP en Agroalimentaire'],
        ['label' => 'LP en Audit et Contrôle de Gestion'],
        ['label' => 'LP en Assurance et Gestion des Risques'],
        ['label' => 'LP en Banque et Finance'],
        ['label' => 'LP en Tourisme et Hôtellerie'],
        ['label' => 'LP en Logistique et Transport'],

    // 'Master'
        ['label' => 'Master en Informatique'],
        ['label' => 'Master en Génie Logiciel'],
        ['label' => 'Master en Intelligence Artificielle'],
        ['label' => 'Master en Data Science'],
        ['label' => 'Master en Cybersécurité'],
        ['label' => 'Master en Réseaux et Télécommunications'],
        ['label' => 'Master en Cloud Computing'],
        ['label' => 'Master en Science des Données'],
        ['label' => 'Master en Mathématiques Appliquées'],
        ['label' => 'Master en Physique'],
        ['label' => 'Master en Chimie'],
        ['label' => 'Master en Biologie'],
        ['label' => 'Master en Biotechnologies'],
        ['label' => 'Master en Sciences de l’Environnement'],
        ['label' => 'Master en Génie Civil'],
        ['label' => 'Master en Génie Mécanique'],
        ['label' => 'Master en Génie Électrique'],
        ['label' => 'Master en Architecture'],
        ['label' => 'Master en Urbanisme'],
        ['label' => 'Master en Énergie Renouvelable'],
        ['label' => 'Master en Économie'],
        ['label' => 'Master en Finance'],
        ['label' => 'Master en Audit et Contrôle de Gestion'],
        ['label' => 'Master en Banque et Finance de Marché'],
        ['label' => 'Master en Comptabilité'],
        ['label' => 'Master en Gestion des Entreprises'],
        ['label' => 'Master en Management'],
        ['label' => 'Master en Management des RH'],
        ['label' => 'Master en Marketing Stratégique'],
        ['label' => 'Master en Commerce International'],
        ['label' => 'Master en Logistique et Transport'],
        ['label' => 'Master en Qualité, Sécurité, Environnement (QSE)'],
        ['label' => 'Master en Droit Public'],
        ['label' => 'Master en Droit Privé'],
        ['label' => 'Master en Droit des Affaires'],
        ['label' => 'Master en Droit Fiscal'],
        ['label' => 'Master en Droit International'],
        ['label' => 'Master en Science Politique'],
        ['label' => 'Master en Administration Publique'],
        ['label' => 'Master en Relations Internationales'],
        ['label' => 'Master en Histoire'],
        ['label' => 'Master en Géographie'],
        ['label' => 'Master en Sociologie'],
        ['label' => 'Master en Psychologie'],
        ['label' => 'Master en Sciences de l’Éducation'],
        ['label' => 'Master en Pédagogie'],
        ['label' => 'Master en Journalisme'],
        ['label' => 'Master en Communication'],
        ['label' => 'Master en Théologie et Études Islamiques'],
        ['label' => 'Master en Tourisme et Hôtellerie'],
        ['label' => 'Master en Santé Publique'],
        ['label' => 'Master en Pharmacie Clinique'],
        ['label' => 'Master en Management de la Santé'],
        ['label' => 'Master en Sciences du Sport'],
        ['label' => 'Master en Arts Visuels'],
        ['label' => 'Master en Design d’Intérieur'],
        ['label' => 'Master en Design Mode'],
        ['label' => 'Master en Affaires Internationales'],

    // 'Master Spécialisé'
        ['label' => 'Master Spécialisé en Gestion de Projet'],
        ['label' => 'Master Spécialisé en Sécurité des Systèmes'],
        ['label' => 'Master Spécialisé en Management Logistique'],
        ['label' => 'Master Spécialisé en Droit Fiscal'],
        ['label' => 'Master Spécialisé en Contrôle de Gestion'],
        ['label' => 'Master Spécialisé en Génie Électrique'],
        ['label' => 'Master Spécialisé en Sciences Politiques'],
        ['label' => 'Master Spécialisé en Assurance Vie et Santé'],
        ['label' => 'Master Spécialisé en Finance de Marché'],

    // 'Doctorat'
        ['label' => 'Doctorat en Informatique'],
        ['label' => 'Doctorat en Droit Public'],
        ['label' => 'Doctorat en Sciences de Gestion'],
        ['label' => 'Doctorat en Biologie Moléculaire'],
        ['label' => 'Doctorat en Sciences Politiques'],
        ['label' => 'Doctorat en Mathématiques Appliquées'],
        ['label' => 'Doctorat en Économie Appliquée'],
        ['label' => 'Doctorat en Sciences de l’Environnement'],
        ['label' => 'Doctorat en CyberSécurité'],

    // 'Certificat de Qualification Professionnelle (CQP)'
        ['label' => 'CQP en Électricité Bâtiment'],
        ['label' => 'CQP en Mécanique Auto'],
        ['label' => 'CQP en Plomberie Sanitaire'],
        ['label' => 'CQP en Coiffure'],
        ['label' => 'CQP en Cuisine Marocaine'],
        ['label' => 'CQP en Réception Hôtelière'],
        ['label' => 'CQP en Maintenance Informatique'],
        ['label' => 'CQP en Assistance RH'],
        ['label' => 'CQP en Gestion de Stock'],

    // 'Certificat de Formation Professionnelle'
        ['label' => 'Agent de Saisie'],
        ['label' => 'Agent de Logistique'],
        ['label' => 'Employé Polyvalent de Restauration'],
        ['label' => 'Aide Comptable'],
        ['label' => 'Aide Boulanger'],
        ['label' => 'Réparateur de Smartphones'],
        ['label' => 'Magasinier'],
        ['label' => 'Opérateur de Production'],
        ['label' => 'Agent de Nettoyage'],
        ['label' => 'Technicien de Maintenance']
    // ]
];

      
    foreach ($diplomaOptions as $option) {
            DiplomaOption::create($option);
        }
    }
}

