<?php

namespace Database\Seeders;

use App\Models\Region;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RegionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $labels = [
            ['label' => 'Afghanistan', 'country_id' => 1],
            ['label' => 'Albanie', 'country_id' => 2],
            ['label' => 'Algerie', 'country_id' => 3],
            ['label' => 'Samoa americaines', 'country_id' => 4],
            ['label' => 'Andorre', 'country_id' => 5],
            ['label' => 'Angola', 'country_id' => 6],
            ['label' => 'Anguilla', 'country_id' => 7],
            ['label' => 'Antigua et Barbuda', 'country_id' => 8],
            ['label' => 'Argentine', 'country_id' => 9],
            ['label' => 'Armenie', 'country_id' => 10],
            ['label' => 'Aruba', 'country_id' => 11],
            ['label' => 'Australie', 'country_id' => 12],
            ['label' => 'Autriche', 'country_id' => 13],
            ['label' => 'Azerbaidjan', 'country_id' => 14],
            ['label' => 'Bahamas', 'country_id' => 15],
            ['label' => 'Bahrein', 'country_id' => 16],
            ['label' => 'Bangladesh', 'country_id' => 17],
            ['label' => 'Barbade', 'country_id' => 18],
            ['label' => 'Bielorussie', 'country_id' => 19],
            ['label' => 'Belgique', 'country_id' => 20],
            ['label' => 'Belize', 'country_id' => 21],
            ['label' => 'Benin', 'country_id' => 22],
            ['label' => 'Bermudes', 'country_id' => 23],
            ['label' => 'Bhoutan', 'country_id' => 24],
            ['label' => 'Bolivie', 'country_id' => 25],
            ['label' => 'Bonaire Saba et Saint Eustache', 'country_id' => 26],
            ['label' => 'Bosnie Herzegovine', 'country_id' => 27],
            ['label' => 'Botswana', 'country_id' => 28],
            ['label' => 'Bresil', 'country_id' => 29],
            ['label' => 'Brunei', 'country_id' => 30],
            ['label' => 'Bulgarie', 'country_id' => 31],
            ['label' => 'Burkina Faso', 'country_id' => 32],
            ['label' => 'Myanmar(Birmanie)', 'country_id' => 33],
            ['label' => 'Burundi', 'country_id' => 34],
            ['label' => 'Cap Vert', 'country_id' => 35],
            ['label' => 'Cambodge', 'country_id' => 36],
            ['label' => 'Cameroun', 'country_id' => 37],
            ['label' => 'Canada', 'country_id' => 38],
            ['label' => 'Iles Caimans', 'country_id' => 39],
            ['label' => 'Republique centrafricaine', 'country_id' => 40],
            ['label' => 'Tchad', 'country_id' => 41],
            ['label' => 'Chili', 'country_id' => 42],
            ['label' => 'Chine', 'country_id' => 43],
            ['label' => 'Ile Christmas', 'country_id' => 44],
            ['label' => 'Colombie', 'country_id' => 45],
            ['label' => 'Comores', 'country_id' => 46],
            ['label' => 'Republique du congo', 'country_id' => 47],
            ['label' => 'Republique democratique du congo', 'country_id' => 48],
            ['label' => 'Iles Cook', 'country_id' => 49],
            ['label' => 'Costa Rica', 'country_id' => 50],
            ['label' => 'Cote dIvoire', 'country_id' => 51],
            ['label' => 'Croatie', 'country_id' => 52],
            ['label' => 'Cuba', 'country_id' => 53],
            ['label' => 'Curacao', 'country_id' => 54],
            ['label' => 'Chypre', 'country_id' => 55],
            ['label' => 'Tchequie', 'country_id' => 56],
            ['label' => 'Danemark', 'country_id' => 57],
            ['label' => 'Djibouti', 'country_id' => 58],
            ['label' => 'Dominique', 'country_id' => 59],
            ['label' => 'Republique dominicaine', 'country_id' => 60],
            ['label' => 'Equateur', 'country_id' => 61],
            ['label' => 'Egypte', 'country_id' => 62],
            ['label' => 'Salvador', 'country_id' => 63],
            ['label' => 'Guinee equatoriale', 'country_id' => 64],
            ['label' => 'Erythree', 'country_id' => 65],
            ['label' => 'Estonie', 'country_id' => 66],
            ['label' => 'Eswatini', 'country_id' => 67],
            ['label' => 'Ethiopie', 'country_id' => 68],
            ['label' => 'Iles Falkland (malvinas)', 'country_id' => 69],
            ['label' => 'Iles Feroe', 'country_id' => 70],
            ['label' => 'Fidji', 'country_id' => 71],
            ['label' => 'Finlande', 'country_id' => 72],
            ['label' => 'France', 'country_id' => 73],
            ['label' => 'Guyane francaise', 'country_id' => 74],
            ['label' => 'Polynesie francaise', 'country_id' => 75],
            ['label' => 'Gabon', 'country_id' => 76],
            ['label' => 'Gambie', 'country_id' => 77],
            ['label' => 'Georgie', 'country_id' => 78],
            ['label' => 'Allemagne', 'country_id' => 79],
            ['label' => 'Ghana', 'country_id' => 80],
            ['label' => 'Gibraltar', 'country_id' => 81],
            ['label' => 'Grece', 'country_id' => 82],
            ['label' => 'Groenland', 'country_id' => 83],
            ['label' => 'Grenade', 'country_id' => 84],
            ['label' => 'Guadeloupe', 'country_id' => 85],
            ['label' => 'Guam', 'country_id' => 86],
            ['label' => 'Guatemala', 'country_id' => 87],
            ['label' => 'Guernesey', 'country_id' => 88],
            ['label' => 'Guinee', 'country_id' => 89],
            ['label' => 'Guinee bissau', 'country_id' => 90],
            ['label' => 'Guyane britannique', 'country_id' => 91],
            ['label' => 'Haiti', 'country_id' => 92],
            ['label' => 'Honduras', 'country_id' => 93],
            ['label' => 'Hong Kong', 'country_id' => 94],
            ['label' => 'Hongrie', 'country_id' => 95],
            ['label' => 'Islande', 'country_id' => 96],
            ['label' => 'Inde', 'country_id' => 97],
            ['label' => 'Indonesie', 'country_id' => 98],
            ['label' => 'Iran', 'country_id' => 99],
            ['label' => 'Irak', 'country_id' => 100],
            ['label' => 'Irlande', 'country_id' => 101],
            ['label' => 'Ile de Man', 'country_id' => 102],
            ['label' => 'Italie', 'country_id' => 103],
            ['label' => 'Jamaique', 'country_id' => 104],
            ['label' => 'Japon', 'country_id' => 105],
            ['label' => 'Jersey', 'country_id' => 106],
            ['label' => 'Jordanie', 'country_id' => 107],
            ['label' => 'Kazakhstan', 'country_id' => 108],
            ['label' => 'Kenya', 'country_id' => 109],
            ['label' => 'Kiribati', 'country_id' => 110],
            ['label' => 'Coree du Nord', 'country_id' => 111],
            ['label' => 'Coree du Sud', 'country_id' => 112],
            ['label' => 'Kosovo', 'country_id' => 113],
            ['label' => 'Koweit', 'country_id' => 114],
            ['label' => 'Kirghizistan', 'country_id' => 115],
            ['label' => 'Laos', 'country_id' => 116],
            ['label' => 'Lettonie', 'country_id' => 117],
            ['label' => 'Liban', 'country_id' => 118],
            ['label' => 'Lesotho', 'country_id' => 119],
            ['label' => 'Liberia', 'country_id' => 120],
            ['label' => 'Libye', 'country_id' => 121],
            ['label' => 'Liechtenstein', 'country_id' => 122],
            ['label' => 'Lituanie', 'country_id' => 123],
            ['label' => 'Luxembourg', 'country_id' => 124],
            ['label' => 'Macao', 'country_id' => 125],
            ['label' => 'Madagascar', 'country_id' => 126],
            ['label' => 'Malawi', 'country_id' => 127],
            ['label' => 'Malaisie', 'country_id' => 128],
            ['label' => 'Maldives', 'country_id' => 129],
            ['label' => 'Mali', 'country_id' => 130],
            ['label' => 'Malte', 'country_id' => 131],
            ['label' => 'Iles Marshall', 'country_id' => 132],
            ['label' => 'Martinique', 'country_id' => 133],
            ['label' => 'Mauritanie', 'country_id' => 134],
            ['label' => 'Maurice', 'country_id' => 135],
            ['label' => 'Mayotte', 'country_id' => 136],
            ['label' => 'Mexique', 'country_id' => 137],
            ['label' => 'Etats federes de Micronesie', 'country_id' => 138],
            ['label' => 'Moldavie', 'country_id' => 139],
            ['label' => 'Monaco', 'country_id' => 140],
            ['label' => 'Mongolie', 'country_id' => 141],
            ['label' => 'Montenegro', 'country_id' => 142],
            ['label' => 'Montserrat', 'country_id' => 143],
            ['label' => 'Béni Mellal-Khénifra', 'country_id' => 144],
            ['label' => 'Casablanca-Settat', 'country_id' => 144],
            ['label' => 'Dakhla-Oued Ed-Dahab', 'country_id' => 144],
            ['label' => 'Drâa-Tafilalet', 'country_id' => 144],
            ['label' => 'Fès-Meknès', 'country_id' => 144],
            ['label' => 'Guelmim-Oued Noun', 'country_id' => 144],
            ['label' => 'L\'Oriental', 'country_id' => 144],
            ['label' => 'Laâyoune-Sakia El Hamra', 'country_id' => 144],
            ['label' => 'Marrakech-Safi', 'country_id' => 144],
            ['label' => 'Rabat-Salé-Kénitra', 'country_id' => 144],
            ['label' => 'Souss-Massa', 'country_id' => 144],
            ['label' => 'Tanger-Tétouan-Al Hoceïma', 'country_id' => 144],
            ['label' => 'Mozambique', 'country_id' => 145],
            ['label' => 'Namibie', 'country_id' => 146],
            ['label' => 'Nauru', 'country_id' => 147],
            ['label' => 'Nepal', 'country_id' => 148],
            ['label' => 'Pays Bas', 'country_id' => 149],
            ['label' => 'Nouvelle Caledonie', 'country_id' => 150],
            ['label' => 'Nouvelle Zelande', 'country_id' => 151],
            ['label' => 'Nicaragua', 'country_id' => 152],
            ['label' => 'Niger', 'country_id' => 153],
            ['label' => 'Nigeria', 'country_id' => 154],
            ['label' => 'Niue', 'country_id' => 155],
            ['label' => 'Ile Norfolk', 'country_id' => 156],
            ['label' => 'Macedoine du Nord', 'country_id' => 157],
            ['label' => 'Iles Mariannes du Nord', 'country_id' => 158],
            ['label' => 'Norvege', 'country_id' => 159],
            ['label' => 'Oman', 'country_id' => 160],
            ['label' => 'Palestine', 'country_id' => 161],
            ['label' => 'Pakistan', 'country_id' => 162],
            ['label' => 'Palaos', 'country_id' => 163],
            ['label' => 'Panama', 'country_id' => 164],
            ['label' => 'Papouasie Nouvelle Guinee', 'country_id' => 165],
            ['label' => 'Paraguay', 'country_id' => 166],
            ['label' => 'Perou', 'country_id' => 167],
            ['label' => 'Philippines', 'country_id' => 168],
            ['label' => 'Iles Pitcairn', 'country_id' => 169],
            ['label' => 'Pologne', 'country_id' => 170],
            ['label' => 'Portugal', 'country_id' => 171],
            ['label' => 'Porto Rico', 'country_id' => 172],
            ['label' => 'Qatar', 'country_id' => 173],
            ['label' => 'Reunion', 'country_id' => 174],
            ['label' => 'Roumanie', 'country_id' => 175],
            ['label' => 'Russie', 'country_id' => 176],
            ['label' => 'Rwanda', 'country_id' => 177],
            ['label' => 'Saint Barthelemy', 'country_id' => 178],
            ['label' => 'Sainte Helene Ascension et Tristan da Cunha', 'country_id' => 179],
            ['label' => 'Saint Christophe et Nieves', 'country_id' => 180],
            ['label' => 'Sainte Lucie', 'country_id' => 181],
            ['label' => 'Saint Pierre et Miquelon', 'country_id' => 182],
            ['label' => 'Saint Vincent et les Grenadines', 'country_id' => 183],
            ['label' => 'Samoa', 'country_id' => 184],
            ['label' => 'Saint Marin', 'country_id' => 185],
            ['label' => 'Sao tome et principe', 'country_id' => 186],
            ['label' => 'Arabie Saoudite', 'country_id' => 187],
            ['label' => 'Senegal', 'country_id' => 188],
            ['label' => 'Serbie', 'country_id' => 189],
            ['label' => 'Seychelles', 'country_id' => 190],
            ['label' => 'Sierra Leone', 'country_id' => 191],
            ['label' => 'Singapour', 'country_id' => 192],
            ['label' => 'Saint Martin', 'country_id' => 193],
            ['label' => 'Slovaquie', 'country_id' => 194],
            ['label' => 'Slovenie', 'country_id' => 195],
            ['label' => 'Iles Salomon', 'country_id' => 196],
            ['label' => 'Somalie', 'country_id' => 197],
            ['label' => 'Afrique du Sud', 'country_id' => 198],
            ['label' => 'Georgie du Sud et iles Sandwich du Sud', 'country_id' => 199],
            ['label' => 'Soudan du Sud', 'country_id' => 200],
            ['label' => 'Espagne', 'country_id' => 201],
            ['label' => 'Sri Lanka', 'country_id' => 202],
            ['label' => 'Soudan', 'country_id' => 203],
            ['label' => 'Suriname', 'country_id' => 204],
            ['label' => 'Svalbard', 'country_id' => 205],
            ['label' => 'Suede', 'country_id' => 206],
            ['label' => 'Suisse', 'country_id' => 207],
            ['label' => 'Syrie', 'country_id' => 208],
            ['label' => 'Taiwan', 'country_id' => 209],
            ['label' => 'Tadjikistan', 'country_id' => 210],
            ['label' => 'Tanzanie', 'country_id' => 211],
            ['label' => 'Thailande', 'country_id' => 212],
            ['label' => 'Timor oriental', 'country_id' => 213],
            ['label' => 'Togo', 'country_id' => 214],
            ['label' => 'Tonga', 'country_id' => 215],
            ['label' => 'Trinite et Tobago', 'country_id' => 216],
            ['label' => 'Tunisie', 'country_id' => 217],
            ['label' => 'Turquie', 'country_id' => 218],
            ['label' => 'Turkmenistan', 'country_id' => 219],
            ['label' => 'Iles Turques et Caiques', 'country_id' => 220],
            ['label' => 'Tuvalu', 'country_id' => 221],
            ['label' => 'Iles Vierges', 'country_id' => 222],
            ['label' => 'Ouganda', 'country_id' => 223],
            ['label' => 'Ukraine', 'country_id' => 224],
            ['label' => 'Emirats arabes unis', 'country_id' => 225],
            ['label' => 'Royaume Uni', 'country_id' => 226],
            ['label' => 'Etats Unis', 'country_id' => 227],
            ['label' => 'Uruguay', 'country_id' => 228],
            ['label' => 'Ouzbekistan', 'country_id' => 229],
            ['label' => 'Vanuatu', 'country_id' => 230],
            ['label' => 'Vatican', 'country_id' => 231],
            ['label' => 'Venezuela', 'country_id' => 232],
            ['label' => 'Viet Nam', 'country_id' => 233],
            ['label' => 'Iles Vierges britanniques', 'country_id' => 234],
            ['label' => 'Wallis et Futuna', 'country_id' => 235],
            ['label' => 'Yemen', 'country_id' => 236],
            ['label' => 'Zambie', 'country_id' => 237],
            ['label' => 'Zimbabwe', 'country_id' => 238],
        ];

        foreach ($labels as $label) {
            Region::create($label);
        }
    }
}
