<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkillTypesSeeder extends Seeder
{
    public function run()
    {
        $data = [
            ['parent_id' => 1, 'label' => 'Achats & Approvisionnements'],
            ['parent_id' => 1, 'label' => 'Administration & Secrétariat'],
            ['parent_id' => 1, 'label' => 'Art & Design'],
            ['parent_id' => 1, 'label' => 'Arts & Culture'],
            ['parent_id' => 1, 'label' => 'Bâtiment & Travaux publics'],
            ['parent_id' => 1, 'label' => 'Commerce & Vente'],
            ['parent_id' => 1, 'label' => 'Comptabilité & Finance'],
            ['parent_id' => 1, 'label' => 'Droit & Juridique'],
            ['parent_id' => 1, 'label' => 'Éducation & Formation'],
            ['parent_id' => 1, 'label' => 'Environnement & Agriculture'],
            ['parent_id' => 1, 'label' => 'Gestion de Projet & Management'],
            ['parent_id' => 1, 'label' => 'Hôtellerie & Restauration'],
            ['parent_id' => 1, 'label' => 'Informatique & Développement'],
            ['parent_id' => 1, 'label' => 'Informatique & Développement - Langages (A-B)'],
            ['parent_id' => 1, 'label' => 'Informatique & Développement - Langages (C)'],
            ['parent_id' => 1, 'label' => 'Informatique & Développement - Langages (D-F)'],
            ['parent_id' => 1, 'label' => 'Informatique & Développement - Langages (Divers/Historiques/Éso.)'],
            ['parent_id' => 1, 'label' => 'Informatique & Développement - Langages (G-H)'],
            ['parent_id' => 1, 'label' => 'Informatique & Développement - Langages (I-L)'],
            ['parent_id' => 1, 'label' => 'Informatique & Développement - Langages (M-P)'],
            ['parent_id' => 1, 'label' => 'Informatique & Développement - Langages (P-R)'],
            ['parent_id' => 1, 'label' => 'Informatique & Développement - Langages (S-T)'],
            ['parent_id' => 1, 'label' => 'Informatique & Développement - Langages (U-W, etc.)'],
            ['parent_id' => 1, 'label' => 'Ingénierie & Industrie'],
            ['parent_id' => 1, 'label' => 'Jeu Vidéo & Animation'],
            ['parent_id' => 1, 'label' => 'Logistique & Supply Chain'],
            ['parent_id' => 1, 'label' => 'Marketing & Communication'],
            ['parent_id' => 1, 'label' => 'QHSE (Qualité, Hygiène, Sécurité...)'],
            ['parent_id' => 1, 'label' => 'Ressources Humaines'],
            ['parent_id' => 1, 'label' => 'Santé & Paramédical'],
            ['parent_id' => 1, 'label' => 'Sciences & Recherche'],
            ['parent_id' => 1, 'label' => 'Social & Services à la personne'],
            ['parent_id' => 1, 'label' => 'Sport & Coaching'],
            ['parent_id' => 1, 'label' => 'Transports & Sécurité'],
            ['parent_id' => 3, 'label' => 'Albanais' ],
            ['parent_id' => 3, 'label' => 'Allemand' ],
            ['parent_id' => 3, 'label' => 'Amérindien' ],
            ['parent_id' => 3, 'label' => 'Anglais' ],
            ['parent_id' => 3, 'label' => 'Arabe' ],
            ['parent_id' => 3, 'label' => 'Arménien' ],
            ['parent_id' => 3, 'label' => 'Azerbaïdjanais' ],
            ['parent_id' => 3, 'label' => 'Basque' ],
            ['parent_id' => 3, 'label' => 'Bengali' ],
            ['parent_id' => 3, 'label' => 'Biélorusse' ],
            ['parent_id' => 3, 'label' => 'Berbère' ],
            ['parent_id' => 3, 'label' => 'Bosnien' ],
            ['parent_id' => 3, 'label' => 'Bulgare' ],
            ['parent_id' => 3, 'label' => 'Catalan' ],
            ['parent_id' => 3, 'label' => 'Chinois' ],
            ['parent_id' => 3, 'label' => 'Coréen' ],
            ['parent_id' => 3, 'label' => 'Croate' ],
            ['parent_id' => 3, 'label' => 'Tchèque' ],
            ['parent_id' => 3, 'label' => 'Danois' ],
            ['parent_id' => 3, 'label' => 'Néerlandais' ],
            ['parent_id' => 3, 'label' => 'Estonien' ],
            ['parent_id' => 3, 'label' => 'Espagnol' ],
            ['parent_id' => 3, 'label' => 'Finnois' ],
            ['parent_id' => 3, 'label' => 'Français' ],
            ['parent_id' => 3, 'label' => 'Galicien' ],
            ['parent_id' => 3, 'label' => 'Géorgien' ],
            ['parent_id' => 3, 'label' => 'Grec' ],
            ['parent_id' => 3, 'label' => 'Gujarati' ],
            ['parent_id' => 3, 'label' => 'Hébreu' ],
            ['parent_id' => 3, 'label' => 'Hindi' ],
            ['parent_id' => 3, 'label' => 'Hongrois' ],
            ['parent_id' => 3, 'label' => 'Icelandais' ],
            ['parent_id' => 3, 'label' => 'Irlandais' ],
            ['parent_id' => 3, 'label' => 'Italien' ],
            ['parent_id' => 3, 'label' => 'Japonais' ],
            ['parent_id' => 3, 'label' => 'Javanais' ],
            ['parent_id' => 3, 'label' => 'Kazakh' ],
            ['parent_id' => 3, 'label' => 'Kurde' ],
            ['parent_id' => 3, 'label' => 'Letton' ],
            ['parent_id' => 3, 'label' => 'Limbourgeois' ],
            ['parent_id' => 3, 'label' => 'Lituanien' ],
            ['parent_id' => 3, 'label' => 'Luxembourgeois' ],
            ['parent_id' => 3, 'label' => 'Macédonien' ],
            ['parent_id' => 3, 'label' => 'Malais' ],
            ['parent_id' => 3, 'label' => 'Maltais' ],
            ['parent_id' => 3, 'label' => 'Marathi' ],
            ['parent_id' => 3, 'label' => 'Monténégrin' ],
            ['parent_id' => 3, 'label' => 'Néerlandais' ],
            ['parent_id' => 3, 'label' => 'Norvégien' ],
            ['parent_id' => 3, 'label' => 'Occitan' ],
            ['parent_id' => 3, 'label' => 'Ourdou' ],
            ['parent_id' => 3, 'label' => 'Polonais' ],
            ['parent_id' => 3, 'label' => 'Portugais' ],
            ['parent_id' => 3, 'label' => 'Pendjabi' ],
            ['parent_id' => 3, 'label' => 'Roumain' ],
            ['parent_id' => 3, 'label' => 'Russe' ],
            ['parent_id' => 3, 'label' => 'Serbe' ],
            ['parent_id' => 3, 'label' => 'Slovaque' ],
            ['parent_id' => 3, 'label' => 'Slovène' ],
            ['parent_id' => 3, 'label' => 'Suédois' ],
            ['parent_id' => 3, 'label' => 'Télougou' ],
            ['parent_id' => 3, 'label' => 'Tamoul' ],
            ['parent_id' => 3, 'label' => 'Turc' ],
            ['parent_id' => 3, 'label' => 'Ukrainien' ],
            ['parent_id' => 3, 'label' => 'Vietnamiens' ],
            ['parent_id' => 3, 'label' => 'Wallon' ],
            ['parent_id' => 3, 'label' => 'Yiddish' ],
            ['parent_id' => 3, 'label' => 'Zulu' ],
            ['parent_id' => 2, 'label' => 'Communication'],
            ['parent_id' => 2, 'label' => 'Gestion du temps'],
            ['parent_id' => 2, 'label' => 'Adaptabilité'],
            ['parent_id' => 2, 'label' => 'Leadership'],
            ['parent_id' => 2, 'label' => 'Empathie'],
            ['parent_id' => 2, 'label' => 'Confiance en soi'],
            ['parent_id' => 2, 'label' => 'Négociation'],
            ['parent_id' => 2, 'label' => 'Créativité'],
            ['parent_id' => 2, 'label' => 'Esprit d\'équipe'],
            ['parent_id' => 2, 'label' => 'Organisation'],
            ['parent_id' => 2, 'label' => 'Résolution de problèmes'],
            ['parent_id' => 2, 'label' => 'Pensée critique'],
            ['parent_id' => 2, 'label' => 'Gestion du stress'],
            ['parent_id' => 2, 'label' => 'Persévérance'],
            ['parent_id' => 2, 'label' => 'Fiabilité'],
            ['parent_id' => 2, 'label' => 'Initiative'],
            ['parent_id' => 2, 'label' => 'Curiosité'],
            ['parent_id' => 2, 'label' => 'Sens du détail'],
            ['parent_id' => 2, 'label' => 'Diplomatie'],
            ['parent_id' => 2, 'label' => 'Exigence de qualité'],
            ['parent_id' => 2, 'label' => 'Prise de décision'],
            ['parent_id' => 2, 'label' => 'Collaboration'],
            ['parent_id' => 2, 'label' => 'Force de proposition'],
            ['parent_id' => 2, 'label' => 'Écoute active'],
            ['parent_id' => 2, 'label' => 'Persuasion'],
            ['parent_id' => 2, 'label' => 'Aisance relationnelle'],
            ['parent_id' => 2, 'label' => 'Transparence'],
            ['parent_id' => 2, 'label' => 'Motivation'],
            ['parent_id' => 2, 'label' => 'Gestion des priorités'],
            ['parent_id' => 2, 'label' => 'Autonomie'],
            ['parent_id' => 2, 'label' => 'Fiabilité technique'],
            ['parent_id' => 2, 'label' => 'Calme'],
            ['parent_id' => 2, 'label' => 'Apprentissage continu'],
            ['parent_id' => 2, 'label' => 'Souci de la satisfaction client'],
            ['parent_id' => 2, 'label' => 'Polyvalence'],
            ['parent_id' => 2, 'label' => 'Discipline'],
            ['parent_id' => 2, 'label' => 'Esprit analytique'],
            ['parent_id' => 2, 'label' => 'Observation'],
            ['parent_id' => 2, 'label' => 'Respect'],
            ['parent_id' => 2, 'label' => 'Gestion des émotions'],
            ['parent_id' => 2, 'label' => 'Humour'],
            ['parent_id' => 2, 'label' => 'Vision globale'],
            ['parent_id' => 2, 'label' => 'Maîtrise de soi'],
            ['parent_id' => 2, 'label' => 'Capacité d\'adaptation culturelle'],
            ['parent_id' => 2, 'label' => 'Gestion de conflits'],
            ['parent_id' => 2, 'label' => 'Coaching'],
            ['parent_id' => 2, 'label' => 'Culture digitale'],
            ['parent_id' => 2, 'label' => 'Diplomatie interne'],
            ['parent_id' => 2, 'label' => 'Force de conviction'],
            ['parent_id' => 2, 'label' => 'Flexibilité'],
            ['parent_id' => 2, 'label' => 'Analyse de risque'],
            ['parent_id' => 2, 'label' => 'Gestion budgétaire'],
            ['parent_id' => 2, 'label' => 'Efficacité personnelle'],
            ['parent_id' => 2, 'label' => 'Gestion documentaire'],
            ['parent_id' => 2, 'label' => 'Gestion de la qualité'],
            ['parent_id' => 2, 'label' => 'Ouverture d\'esprit'],
            ['parent_id' => 2, 'label' => 'Maîtrise du langage écrit'],
            ['parent_id' => 2, 'label' => 'Maîtrise du langage oral'],
            ['parent_id' => 2, 'label' => 'Gestion de projet'],
            ['parent_id' => 2, 'label' => 'Médiation'],
            ['parent_id' => 2, 'label' => 'Langues étrangères'],
            ['parent_id' => 2, 'label' => 'Travail d\'équipe'],
            ['parent_id' => 2, 'label' => 'Vision stratégique'],
            ['parent_id' => 2, 'label' => 'Endurance'],
            ['parent_id' => 2, 'label' => 'Force de travail'],
            ['parent_id' => 2, 'label' => 'Adaptation technologique'],
            ['parent_id' => 2, 'label' => 'Accessibilité'],
            ['parent_id' => 2, 'label' => 'Orientation résultats'],
            ['parent_id' => 2, 'label' => 'Éthique'],
            ['parent_id' => 2, 'label' => 'Autocritique'],
            ['parent_id' => 2, 'label' => 'Gestion multi-projets'],
            ['parent_id' => 2, 'label' => 'Jugement'],
            ['parent_id' => 2, 'label' => 'Souplesse relationnelle'],
            ['parent_id' => 2, 'label' => 'Appui technique'],
            ['parent_id' => 2, 'label' => 'Culture générale'],
            ['parent_id' => 2, 'label' => 'Optimisme'],
            ['parent_id' => 2, 'label' => 'Relation client'],
            ['parent_id' => 2, 'label' => 'Dynamisme'],
            ['parent_id' => 2, 'label' => 'Précision'],
            ['parent_id' => 2, 'label' => 'Gout du challenge'],
            ['parent_id' => 2, 'label' => 'Networking'],
            ['parent_id' => 2, 'label' => 'Implication'],
            ['parent_id' => 2, 'label' => 'Professionnalisme'],
            ['parent_id' => 2, 'label' => 'Gout de l\'effort'],
            ['parent_id' => 2, 'label' => 'Curiosité intellectuelle'],
            ['parent_id' => 2, 'label' => 'Souci esthétique'],
            ['parent_id' => 2, 'label' => 'Gestion de l\'incertitude'],
            ['parent_id' => 2, 'label' => 'Force de caractère'],
            ['parent_id' => 2, 'label' => 'Proactivité'],
            ['parent_id' => 2, 'label' => 'Culture de la sécurité'],
            ['parent_id' => 2, 'label' => 'Courtoisie'],
            ['parent_id' => 2, 'label' => 'Relation de confiance'],
            ['parent_id' => 2, 'label' => 'Gestion des ressources'],
            ['parent_id' => 2, 'label' => 'Documentation'],
            ['parent_id' => 2, 'label' => 'Gestion d\'événements'],
            ['parent_id' => 2, 'label' => 'Sincérité'],
            ['parent_id' => 2, 'label' => 'Mobilisation'],
            ['parent_id' => 2, 'label' => 'Relationnel client délicat'],
            ['parent_id' => 2, 'label' => 'Gestion des urgences'],
            ['parent_id' => 2, 'label' => 'Connaissance de soi'],
            ['parent_id' => 2, 'label' => 'Gestion des imprévus'],
            ['parent_id' => 2, 'label' => 'Vision long terme'],
            ['parent_id' => 2, 'label' => 'Maîtrise bureautique'],
            ['parent_id' => 2, 'label' => 'Patience'],
            ['parent_id' => 2, 'label' => 'Allocation des ressources'],
            ['parent_id' => 2, 'label' => 'Relation interpersonnelle'],
            ['parent_id' => 2, 'label' => 'Communication non verbale'],
            ['parent_id' => 2, 'label' => 'Leadership d\'opinion'],
            ['parent_id' => 2, 'label' => 'Perspicacité'],
            ['parent_id' => 2, 'label' => 'Gestion d\'équipe'],
            ['parent_id' => 2, 'label' => 'Gestion de l\'information'],
            ['parent_id' => 2, 'label' => 'Assertivité'],
            ['parent_id' => 2, 'label' => 'Orientation client'],
            ['parent_id' => 2, 'label' => 'Anticipation'],
            ['parent_id' => 2, 'label' => 'Relation de mentorat'],
            ['parent_id' => 2, 'label' => 'Gestion de l\'équilibre vie pro/perso'],
            ['parent_id' => 2, 'label' => 'Endurance mentale'],
            ['parent_id' => 2, 'label' => 'Gestion des émotions collectives'],
            ['parent_id' => 2, 'label' => 'Polyculture'],
            ['parent_id' => 2, 'label' => 'Langage corporel'],
            ['parent_id' => 2, 'label' => 'Esprit entrepreneurial'],
            ['parent_id' => 2, 'label' => 'Empowement d\'équipe'],
            ['parent_id' => 2, 'label' => 'Gestion de la diversité'],
            ['parent_id' => 2, 'label' => 'Humilité'],
            ['parent_id' => 2, 'label' => 'Gestion de crise'],
        ];

        DB::table('skill_types')->insert($data);
    }
}
